// pages/f-svelte/src/lib/ModCard.svelte
<script>
  import { BADGE, fmtDl } from './mods.js'
  let { mod, onclick } = $props()
</script>

<div class="card" onclick={() => onclick(mod)}>
  <span class="badge {BADGE[mod.category] ?? 'badge-other'}">{mod.category}</span>
  <div class="card-name">{mod.name}</div>
  <div class="card-meta">
    <span>{mod.author || 'Unknown'}</span>
    <span class="card-dl">↓ {fmtDl(mod.downloads)}</span>
  </div>
  {#if mod.description}
    <p class="card-desc">{mod.description}</p>
  {/if}
  <div class="card-actions">
    <a class="btn btn-primary" href={mod.download_url} target="_blank"
       onclick={e => e.stopPropagation()}>Download</a>
    <a class="btn" href={mod.page_url} target="_blank"
       onclick={e => e.stopPropagation()}>Info</a>
  </div>
</div>

// pages/g-react/src/components/ModCard.jsx
import { BADGE, fmtDl } from '../mods.js'

export default function ModCard({ mod, onClick }) {
  return (
    <div className="card" onClick={() => onClick(mod)}>
      <span className={`badge ${BADGE[mod.category] ?? 'badge-other'}`}>
        {mod.category}
      </span>
      <div className="card-name">{mod.name}</div>
      <div className="card-meta">
        <span>{mod.author || 'Unknown'}</span>
        <span className="card-dl">↓ {fmtDl(mod.downloads)}</span>
      </div>
      {mod.description && <p className="card-desc">{mod.description}</p>}
      <div className="card-actions">
        <a className="btn btn-primary" href={mod.download_url} target="_blank" rel="noreferrer"
           onClick={e => e.stopPropagation()}>Download</a>
        <a className="btn" href={mod.page_url} target="_blank" rel="noreferrer"
           onClick={e => e.stopPropagation()}>Info</a>
      </div>
    </div>
  )
}
